name: Deploy to Amazon ECS

on:
  workflow_call:
    inputs:
      image_tag:
        description: Image tag to deploy
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      image_tag:
        description: Image tag to deploy
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: choice
        options:
          - staging
          - production
        default: staging

env:
  SERVICE_NAME: test-world

permissions:
  contents: read

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install envsub
        run: npm install -g envsub

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          #ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          ECR_REPOSITORY: bitovi-devops-training-ec2-gha-example-simple-ecr-ecr
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          # Build a docker container and push it to ECR
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

          # Add extra tag for the environment
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
                     $ECR_REGISTRY/$ECR_REPOSITORY:${{ inputs.environment }}

          # Push both tags
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ inputs.environment }}

          # Output the image reference
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Substitute environment variables in task definition
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          #ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          ECR_REPOSITORY: bitovi-devops-training-ec2-gha-example-simple-ecr-ecr
          IMAGE_TAG: ${{ inputs.image_tag }}
          ENVIRONMENT: ${{ inputs.environment }}
          AWS_REGION: us-east-1 #${{ vars.AWS_REGION }}
          #TASK_DEFINITION_FAMILY: ${{ vars.TASK_DEFINITION_FAMILY }}
          TASK_DEFINITION_FAMILY: test-world-task
          #TASK_CPU: ${{ vars.TASK_CPU }}
          #TASK_MEMORY: ${{ vars.TASK_MEMORY }}
          TASK_CPU: 256
          TASK_MEMORY: 512
          #EXECUTION_ROLE_ARN: "arn:aws:iam::755521597925:role/ecsTaskExecutionRole-staging"
          #TASK_ROLE_ARN: "arn:aws:iam::755521597925:role/ecsTaskRole-staging"
          #CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
          CONTAINER_NAME: test-world
          CLOUDWATCH_LOG_GROUP: test-world-cloudwatch-log-group
          CLOUDWATCH_LOG_STREAM_PREFIX: test-world-cloudwatch-log-stream
          APP_VERSION: ${{ inputs.image_tag }}
        run: |
          envsub task-definition.template.json task-definition.json

      #- name: Fill in the new image ID in the Amazon ECS task definition
      #  id: task-def
      #  uses: aws-actions/amazon-ecs-render-task-definition@v1
      #  with:
      #    task-definition: task-definition.json
      #    container-name: test-world
      #    image: ${{ steps.build-image.outputs.image }}

      #- name: Deploy Amazon ECS task definition
      #  uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      #  with:
      #    task-definition: ${{ steps.task-def.outputs.task-definition }}
      #    service: test-world-service
      #    cluster: test-world-cluster
      #    wait-for-service-stability: true

      - name: Deploy using GHA
        uses: bitovi/github-actions-deploy-ecs@v0.1.5
        id: ecs
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: us-east-1

          aws_ecs_task_name: test-world
          aws_ecs_task_json_definition_file: task-definition.json

          #tf_stack_destroy: true # This is to destroy the stack
          tf_state_bucket_destroy: true # Will only destroy the bucket if tf_stack_destroy is true

          aws_ecs_task_cpu: 256
          aws_ecs_task_mem: 512
          aws_ecs_app_image: ${{ inputs.image_tag }} #nginx:latest
          aws_ecs_assign_public_ip: false # true

          aws_ecs_container_port: 3000
          aws_ecs_lb_port: 3000

            #"executionRoleArn": "${EXECUTION_ROLE_ARN}",
            #"taskRoleArn": "${TASK_ROLE_ARN}",