name: Deploy EKS Cluster

on:
  push:
    branches: [ deploy-eks ]
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: deploy
      uses: bitovi/github-actions-deploy-eks@deploy-eks
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws_default_region: us-east-1

        input_helm_charts: helm
  
        bitops_code_only: 
        bitops_code_store: 
        tf_state_bucket_destroy: true
        
        aws_eks_create: 
        aws_eks_region: 
        aws_eks_security_group_name_master: 
        aws_eks_security_group_name_worker: 
        aws_eks_environment:
        aws_eks_stackname: 
        aws_eks_cidr_block:
        aws_eks_workstation_cidr: 
        aws_eks_availability_zones: 
        aws_eks_private_subnets: 
        aws_eks_public_subnets: 
        aws_eks_cluster_name: 
        aws_eks_cluster_log_types: 
        aws_eks_cluster_version:
        aws_eks_instance_type: 
        aws_eks_user_data_file: 
        aws_eks_ec2_key_pair:
        aws_eks_store_keypair_sm: true
        aws_eks_desired_capacity: 
        aws_eks_max_size: 
        aws_eks_min_size:
 
