on:
  push:
    branches: [ d2ec2 ]

permissions:
  contents: read
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    #environment:
     # name: ${{ github.ref_name }}
     # url: ${{ steps.deploy.outputs.lb_url }}
    # #   
    steps:
      - id: deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_elb_app_port: 3000
          aws_ec2_instance_type: t3.small
          tf_state_bucket_destroy: true
          #aws_efs_fs_id: fs-0a74d7a05adeb2c55
          bitops_code_only: true
          bitops_code_store: true
          
          #tf_stack_destroy: true
# why not?  go
