name: Deploy GHR
on:
  push:
    branches: [ ecr-ecs-fargate ]
      

jobs:
  deploy-bucket-only:
    runs-on: ubuntu-latest
    steps:
    - name: Build tag and push container
      id: tag-and-push
      uses: bitovi/github-actions-ecr-publish@main
      with:
        checkout: true
        aws_login: true
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws_default_region: us-east-1
        aws_ecr_repo_name: testing-repo-leo
        #image_tag:
        #org_name:
        #build_args:
        use_latest: true
        working_directory: container

    #- name: Create an RDS DB
    #  id: create-rds
    #  uses: bitovi/github-actions-deploy-rds@testing
    #  with:
    #    aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
    #    aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
    #    aws_default_region: us-east-1
    #    
    #    tf_stack_destroy: true
    #    tf_state_bucket_destroy: true
        
    #    aws_rds_db_enable: true
