name: Deploy Pixel Tracker Sandbox

on:
  push:
    branches: [ pixel ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Bitovi's Deploy Pixel Tracker 
    - id: deploy
      name: Deploy
      uses: bitovi/github-actions-deploy-pixel-tracker@fix-long-term-storage
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}

        tf_stack_destroy: true
        tf_state_bucket_destroy: true

        aws_ec2_instance_type: t3.small
        
        aws_domain_name: bitovi-sandbox.com
        #prometheus_scrape_interval: 1h
        #prometheus_retention_period: 365d
        
        #grafana_scrape_interval: 1h
        cadvisor_enable: true
        node_exporter_enable: true
        print_yaml_files: true

        aws_ec2_port_list: 9090,8080,3000,9100
        env_ghs: ${{ vars.PIXEL }}
