name: Deploy GHR
on:
  push:
    branches: [ ecr-ecs-fargate ]
jobs:
  deploy-bucket-only:
    runs-on: ubuntu-latest
    steps:
    #- name: Create an ECS-Fargate deploy
    #  uses: bitovi/github-actions-deploy-aws-ecr-registry@main
    #  id: ecr
    #  with:
    #    aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
    #    aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
    #    aws_default_region: us-east-1
    #    tf_stack_destroy: true
    #    tf_state_bucket_destroy: true
    - name: Create an RDS DB
      id: create-rds
      uses: bitovi/github-actions-deploy-rds@main
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws_default_region: us-east-1
    # #   
        tf_state_bucket_destroy: true
       # tf_state_file_name_append: rds
        tf_stack_destroy: true
        aws_rds_db_enable: true
     #     aws_rds_db_proxy: true
        aws_rds_db_name: postgres
        aws_rds_db_ingress_allow_all: true
        aws_rds_db_publicly_accessible: true
        aws_rds_db_ca_cert_identifier: rds-ca-ecc384-g1
     #     aws_db_proxy_allowed_security_group: sg-0d93315ea70f0f860
     #     aws_db_proxy_allow_all_incoming: true