name: Deploy-PR

on:
  pull_request:
    branches: [ feature-commonscripts ]
  workflow_dispatch:
    inputs:
      stack_destroy:  
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  EC2-Deploy:
    # if the branch name of the PR does not contain 'skip-deploy'
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
    - id: deploy
      name: Deploy
      uses: bitovi/github-actions-deploy-docker-to-ec2@feature-commontest
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_DEVOPS_TRAINING}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVOPS_TRAINING}}
        aws_default_region: us-east-1
        app_port: 3000
        stack_destroy: ${{ github.event.inputs.stack_destroy }}

    - if: ${{ steps.deploy.outputs.vm_url != '' }}
      name: Print result created
      run: |
        echo "## VM Created! :rocket:" >> $GITHUB_STEP_SUMMARY
        echo " ${{ steps.deploy.outputs.vm_url }}" >> $GITHUB_STEP_SUMMARY
    - if: ${{ steps.deploy.outputs.vm_url == '' }}
      name: Print result destroyed
      run: |
        echo "## VM Destroyed! :boom:" >> $GITHUB_STEP_SUMMARY
        echo "Buckets and whole infrastructure should be gone now!" >> $GITHUB_STEP_SUMMARY
