name: Deploy ST2 Single VM with GHA

on:
  push:
    branches: [ st2 ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.lb_url }}

    steps:

    # Foresight's GitHub Action Monitoring workflow action
    # Make sure you put workflow kit action on top of all the steps 
    - name: Collect Workflow Telemetry
      uses: runforesight/foresight-workflow-kit-action@v1
      if: ${{ always() }}
      with:
        api_key: ${{ secrets.FORESIGHT_API_KEY }}

    # Bitovi's Deploy StackStorm action
    - id: deploy
      name: Deploy
      uses: bitovi/github-actions-deploy-stackstorm@v0.3.0
      #uses: bitovi/github-actions-deploy-stackstorm@commons
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        #aws_ec2_instance_type: t2.small
        tf_stack_destroy: true
        tf_state_bucket_destroy: true
        
        aws_default_region: us-east-1
        st2_auth_username: ${{ secrets.ST2_AUTH_USERNAME_GHA_SINGLEVM_TESTU}}
        st2_auth_password: ${{ secrets.ST2_AUTH_PASSWORD_GHA_SINGLEVM_TESTU}}
        st2_packs: "st2, https://github.com/bitovi-stackstorm-exchange/incident_reduction.git"
        st2_ansible_extra_vars_file: "st2_vars.yaml"

        #infrastructure_only: true
        #
        aws_domain_name: bitovi-sandbox.com
        aws_sub_domain: st2-test-leo
        #create_sub_cert: true
        #no_cert: true
