name: Deploy D2EC2 Testing branch

on:
  push:
    branches: [ d2ec2 ]

permissions:
  contents: read
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.lb_url }}

    steps:
    # Bitovi's Deploy StackStorm action
    #- id: deploy
    #  name: Deploy
    #  uses: bitovi/github-actions-deploy-stackstorm@commons
    #  with:
    #    aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
    #    aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}

    #    tf_stack_destroy: 
    #    tf_state_file_name_append: st2demo
    #    tf_state_bucket_destroy: true
        
    #    aws_default_region: us-east-1
    #    st2_packs: "st2"
        #st2_ansible_extra_vars_file: "st2_vars.yaml"
    #    st2_auth_username: st2demo
    #    st2_auth_password: ${{ secrets.ST2_DEMO }}
        
    #    aws_domain_name: bitovi-sandbox.com
    #    aws_sub_domain: st2-demo
        #create_sub_cert: true
        #no_cert: true
        
    - id: deploy2
      uses: bitovi/github-actions-deploy-docker-to-ec2@commons
      with:
        #ansible_skip: true

        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws_default_region: us-east-1
        #tf_state_bucket_destroy: true
        #stack_destroy: true
        ec2_port_list: 3001
        app_port: 3001
        lb_port: 3001
        tf_state_file_name_append: d2ec2
       # lb_healthcheck: "HTTP:3001"
     #   ec2_volume_size: 16
     #   aws_rds_db_enable: 
     #   docker_remove_orphans: true

    #- name: Create an RDS DB
    #  id: create-rds
    #  uses: bitovi/github-actions-deploy-rds@multiple-fixes
    #  with:
    #    aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
    #    aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
    #    aws_default_region: us-east-1
    #    
    #    tf_state_bucket_destroy: true
    #    tf_stack_destroy: true
    #    aws_rds_db_enable: true
    #    aws_rds_db_proxy: true
    #    aws_rds_db_name: postgresdevelopment
    #- id: ecr-publish
    #  name: Build image
    #  uses: bitovi/github-actions-ecr-publish@v0.1.0
    #  with:
    #    aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
    #    aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
    #    aws_default_region: us-east-1
    #    aws_ecr_repo_name: testing-repo-leo
    #    image_tag: auth
    #- run: |
    #    echo "Image Created:  ${{ env.image }}"
    #    echo "Tag Created: ${{ env.tag }}"
