name: Verify and Deploy

on: [push]

jobs:
  verify-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: bitovi/github-actions-deploy-static-site-to-aws@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
          aws_default_region: us-east-1
  
          tf_action: 'destroy'
          tf_state_bucket_destroy: true
          #aws_resource_identifier: bitovi-devops-training-ec2-gha-example-static-site
          aws_site_cdn_enabled: false
          # You should own and have this domain available in R53
          aws_r53_domain_name: bitovi-sandbox.com
          #aws_r53_sub_domain_name: bitovi-devops-training-ec2-gha-example-static-site
          aws_r53_create_sub_cert: true # Will create and validate a cert for this sub-domain

