name: Deploy D2EC2 Testing branch

on:
  push:
    branches: [ d2ec2 ]

permissions:
  contents: read

jobs:
  EC2-Deploy:
    # if the branch name of the PR does not contain 'skip-deploy'
    if: "!contains(github.head_ref, 'skip-deploy')"
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
    - id: deploy
      name: Deploy
      uses: bitovi/github-actions-deploy-docker-to-ec2@commons-commons
      with:
        # Action defaults inputs
        checkout: true
        #stack_destroy: true
        
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws_default_region: us-east-1
        
        # Provide a secret called `DOT_ENV` to append environment variables to the .env file
        dot_env: ${{ secrets.DOT_ENV }}

        # EC2 Inputs
        aws_ami_id: ami-06878d265978313ca
        create_keypair_sm_entry: true
        ec2_instance_type: t2.medium
        
        # EFS Inputs
        #aws_create_efs: true
        aws_create_ha_efs: true
        #aws_create_efs_replica: true
        #aws_enable_efs_backup_policy: true
        
        # RDS Inputs
        #aws_enable_postgres: true
        #aws_postgres_database_name: db_name
        #aws_postgres_database_port: 5435

        # Certificate Inputs
        domain_name: bitovi-sandbox.com
        sub_domain: d2ec2
        create_sub_cert: true
        #no_cert: true

        # Application Inputs
        lb_port: 3000
        
        # Terraform inputs
        tf_state_bucket_destroy: true 
        
# Nothing should change - again
