name: Basic deploy
on:
  push:
    branches: [ prometheus ]

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    steps:
    - id: deploy
      name: Deploy
      uses: bitovi/github-actions-deploy-prometheus@Addding-prometheus-and-grafana-scrapping-options
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        tf_state_bucket_destroy: true
        #tf_stack_destroy: true
        prometheus_scrape_interval: 60m
        prometheus_retention_period: 365d
