name: Deploy

on:
  push:
    branches: [ testing-gha-d2ec2 ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: vm_url
      url: ${{ steps.deploy.vm_url }}
    steps:
    - id: deploy
      uses: bitovi/github-actions-deploy-docker-to-ec2@42-surface-dns-records
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_DEVOPS_TRAINING}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVOPS_TRAINING}}
        aws_default_region: us-east-1
        #stack_destroy: true

        # Provide a secret called `DOT_ENV` to append environment variables to the .env file
        # dot_env: ${{ secrets.DOT_ENV }}

        app_port: 3000
    - id: summary
      run: |
        echo "## VM Created! :rocket:" >> $GITHUB_STEP_SUMMARY
        echo "VM Public URL: $vm_url" >> $GITHUB_STEP_SUMMARY
