name: Deploy ST2 Single VM with GHA

on:
  push:
    branches: [ st2 ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.lb_url }}

    steps:
    # Bitovi's Deploy StackStorm action
    - id: deploy
      name: Deploy
      uses: bitovi/github-actions-deploy-stackstorm@commons
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}

        tf_stack_destroy: 
        tf_state_bucket_destroy: true
        
        aws_default_region: us-east-1
        st2_auth_username: karam
        st2_auth_password: ${{ secrets.KARAM_ST2 }}
        st2_packs: "st2"
        #st2_ansible_extra_vars_file: "st2_vars.yaml"

        aws_domain_name: bitovi-sandbox.com
        aws_sub_domain: st2-karam
        #create_sub_cert: true
        #no_cert: true
        aws_ec2_create_keypair_sm: true
