name: Deploy GHR
on:
  push:
    branches: [ ecr-ecs-fargate ]
      

jobs:
  deploy-bucket-only:
    runs-on: ubuntu-latest
    steps:
#    - name: Build tag and push container
#      id: tag-and-push
#      uses: bitovi/github-actions-ecr-publish@main
#      with:
#        checkout: true
#        aws_login: true
#        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
#        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
#        aws_default_region: us-east-1
#        aws_ecr_repo_name: testing-repo-leo
        #image_tag:
        #org_name:
        #build_args:
#        use_latest: true
#        working_directory: container

    - name: Create an ECS-Fargate deploy
      uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws_default_region: us-east-1

        stack_destroy: 
        tf_state_bucket: ecs-leo-testing
        tf_state_bucket_destroy: 
        #aws_vpc_id: vpc-081abe910edab4281
        #aws_vpc_subnet_id: subnet-056feca23aa09e324
        
        aws_ecs_enable: true
        #aws_ecs_service_name: a
        #aws_ecs_cluster_name: b
        aws_ecs_task_name: auth
        #aws_ecs_task_execution_role: ecsTaskExecutionRole
        aws_ecs_task_json_definition_file: cs.json
        aws_ecs_task_network_mode: awsvpc
        aws_ecs_task_cpu: 2048
        aws_ecs_task_mem: 6144
        #aws_ecs_container_cpu: 1024,1024,512,512
        #aws_ecs_container_mem: 2048,2048,1024,1024
        aws_ecs_node_count: 1
        #aws_ecs_app_image: 755521597925.dkr.ecr.us-east-1.amazonaws.com/testing-repo-leo:auth,755521597925.dkr.ecr.us-east-1.amazonaws.com/testing-repo-leo:d2ec2,755521597925.dkr.ecr.us-east-1.amazonaws.com/testing-repo-leo:hello
        #aws_ecs_image_path: ',api'
        #aws_ecs_security_group_name: somesgname
        aws_ecs_assign_public_ip: true
        aws_ecs_container_port: 8080
        aws_ecs_lb_port: 8080
        aws_ecs_lb_redirect_enable: true
        aws_ecs_cloudwatch_enable: true
        #aws_ecs_cloudwatch_lg_name: ecstest
        aws_ecs_cloudwatch_skip_destroy: false
        aws_ecs_cloudwatch_retention_days: 7
        aws_ecs_additional_tags: 

        #aws_ecs_autoscaling_enable: false
        #aws_ecs_autoscaling_max_nodes: 3,2,3,1
        #aws_ecs_autoscaling_min_nodes: 1,1,1,1
        #aws_ecs_autoscaling_max_mem: 77,78,79,80
        #aws_ecs_autoscaling_max_cpu: 77,78,79,80

        #ghv_env: ${{ vars.TEST_VARS }}
        #dot_env: ${{ secrets.KV_SECRET_TEST }}
        aws_r53_enable: true
        domain_name: bitovi-sandbox.com
        sub_domain: ecs-testing
        tf_state_file_name_append: tbd
