name: Deploy-PR

on:
  pull_request:
    branches: [ feature-commonscripts ]
  workflow_dispatch:
    inputs:
      stack_destroy:  
        type: boolean
        default: false
      stack_deploy:  
        type: boolean
        default: false  

permissions:
  contents: read


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: deploy
      name: Deploy
      uses: bitovi/github-actions-deploy-docker-to-ec2@v0.4.6
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1
        stack_destroy: ${{ github.event.inputs.stack_destroy  }}
