name: Deploy

on:
  push:
    branches: [ testing-gha-d2ec2 ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      vm_url: ${{ steps.deploy.vm_url }}
    steps:
    - id: EC2-Deploy
      uses: bitovi/github-actions-deploy-docker-to-ec2@42-surface-dns-records
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_DEVOPS_TRAINING}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVOPS_TRAINING}}
        aws_default_region: us-east-1
        #stack_destroy: true

        # Provide a secret called `DOT_ENV` to append environment variables to the .env file
        # dot_env: ${{ secrets.DOT_ENV }}

        app_port: 3000
    - if: ${{ stack_destroy != 'true' }}
      run: |
        echo "## VM Created! :rocket:" >> $GITHUB_STEP_SUMMARY
        echo " ${{ steps.deploy.outputs.vm_url }}" >> $GITHUB_STEP_SUMMARY
    - if: ${{ stack_destroy == 'true' }}
      run: |
        echo "## VM Destroyed! :boom:" >> $GITHUB_STEP_SUMMARY
        echo "Buckets and whole infrastructure should be gone now!"