name: Deploy

on:
  push:
    # TODO: uncomment before merge
    # branches: [ main ]
    # TODO: remove before merge
    branches: [ fix-instance-profile ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: deploy
      uses: bitovi/github-actions-node-app-to-aws-vm@add-ansible-nocache
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_DEVOPS_TRAINING}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVOPS_TRAINING}}
        aws_default_region: us-east-1

        # Provide a secret called `DOT_ENV` to append environment variables to the .env file
        # dot_env: ${{ secrets.DOT_ENV }}

        app_port: 3000