name: Deploy EKS Cluster

on:
  push:
    branches: [ deploy-eks ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Create EKS Cluster
      uses: bitovi/github-actions-deploy-eks@Upgrade-commons-version
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1
        
        tf_state_bucket_destroy: true
        tf_stack_destroy: true
        aws_eks_cluster_admin_role_arn: arn:aws:iam::755521597925:role/AWSReservedSSO_AdministratorAccess_402f22a297379e03
        aws_eks_create: true
        # input_helm_charts:
        prometheus_enable: true
        grafana_enable: true
