name: Verify and Deploy

on: [push]

env:
  TF_ACTION: 'apply'

jobs:
  verify-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Go SPA No Cache
        uses: bitovi/github-actions-deploy-static-site-to-aws@v0.2.8
        #add-caching-to-cdn 
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1
  
          #aws_site_source_folder: .
          tf_action: ${{ env.TF_ACTION}}
          tf_state_bucket_destroy: true
          aws_resource_identifier: bitovi-devops-training-ec2-gha-example-static-site-nc
          #aws_site_cdn_custom_error_codes: '{error_caching_min_ttl:"0",error_code:"403",response_code:"200",response_page_path:"/custom_404.html"}'
          aws_site_cdn_custom_error_codes: '[{\"error_caching_min_ttl\":\"0\",\"error_code\":\"403\",\"response_code\":\"200\",\"response_page_path\":\"/index.html\"},{\"error_caching_min_ttl\":\"0\",\"error_code\":\"404\",\"response_code\":\"200\",\"response_page_path\":\"/index.html\"}]'
          # You should own and have this domain available in R53
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: static-site-test-nc
          aws_site_cdn_enabled: true
          #aws_site_cdn_min_ttl: 0
          #aws_site_cdn_default_ttl: 172800  # 48 hours
          #aws_site_cdn_max_ttl: 604800      # 7 days          #aws_site_cdn_aliases: static-site-test.bitovi-sandbox.com,static-site-test2.bitovi-sandbox.com
          #aws_site_cdn_response_headers_policy_id: "eaab4381-ed33-4a86-88ca-d9558dc6cd63"
          aws_r53_create_sub_cert: true # Will create and validate a cert for this sub-domain
          aws_site_source_include_hidden: false

      - name: Go SPA old Cache
        uses: bitovi/github-actions-deploy-static-site-to-aws@v0.2.8
        #add-caching-to-cdn 
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1
  
          #aws_site_source_folder: .
          tf_action: ${{ env.TF_ACTION}}
          tf_state_bucket_destroy: true
          aws_resource_identifier: bitovi-devops-training-ec2-gha-example-static-site-oc
          #aws_site_cdn_custom_error_codes: '{error_caching_min_ttl:"0",error_code:"403",response_code:"200",response_page_path:"/custom_404.html"}'
          aws_site_cdn_custom_error_codes: '[{\"error_caching_min_ttl\":\"0\",\"error_code\":\"403\",\"response_code\":\"200\",\"response_page_path\":\"/index.html\"},{\"error_caching_min_ttl\":\"0\",\"error_code\":\"404\",\"response_code\":\"200\",\"response_page_path\":\"/index.html\"}]'
          # You should own and have this domain available in R53
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: static-site-test-oc
          aws_site_cdn_enabled: true
          aws_site_cdn_min_ttl: 11
          aws_site_cdn_default_ttl: 172801  # 48 hours
          aws_site_cdn_max_ttl: 604801      # 7 days          #aws_site_cdn_aliases: static-site-test.bitovi-sandbox.com,static-site-test2.bitovi-sandbox.com
          #aws_site_cdn_response_headers_policy_id: "eaab4381-ed33-4a86-88ca-d9558dc6cd63"
          aws_r53_create_sub_cert: true # Will create and validate a cert for this sub-domain
          aws_site_source_include_hidden: false

      - name: Go SPA old Cache + CORS
        uses: bitovi/github-actions-deploy-static-site-to-aws@v0.2.8
        #add-caching-to-cdn 
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1
  
          #aws_site_source_folder: .
          tf_action: ${{ env.TF_ACTION}}
          tf_state_bucket_destroy: true
          aws_resource_identifier: bitovi-devops-training-ec2-gha-example-static-site-occ
          #aws_site_cdn_custom_error_codes: '{error_caching_min_ttl:"0",error_code:"403",response_code:"200",response_page_path:"/custom_404.html"}'
          aws_site_cdn_custom_error_codes: '[{\"error_caching_min_ttl\":\"0\",\"error_code\":\"403\",\"response_code\":\"200\",\"response_page_path\":\"/index.html\"},{\"error_caching_min_ttl\":\"0\",\"error_code\":\"404\",\"response_code\":\"200\",\"response_page_path\":\"/index.html\"}]'
          # You should own and have this domain available in R53
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: static-site-test-occ
          aws_site_cdn_enabled: true
          aws_site_cdn_min_ttl: 22
          aws_site_cdn_default_ttl: 172802  # 48 hours
          aws_site_cdn_max_ttl: 604802      # 7 days          #aws_site_cdn_aliases: static-site-test.bitovi-sandbox.com,static-site-test2.bitovi-sandbox.com
          aws_site_cdn_response_headers_policy_id: "eaab4381-ed33-4a86-88ca-d9558dc6cd63"
          aws_r53_create_sub_cert: true # Will create and validate a cert for this sub-domain
          aws_site_source_include_hidden: false

      - name: Go SPA Full
        uses: bitovi/github-actions-deploy-static-site-to-aws@add-cache-control-if-aws_site_cdn_default_ttl-is-set
        #add-caching-to-cdn 
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1
  
          #aws_site_source_folder: .
          tf_action: ${{ env.TF_ACTION}}
          tf_state_bucket_destroy: true
          aws_resource_identifier: bitovi-devops-training-ec2-gha-example-static-site-c
          #aws_site_cdn_custom_error_codes: '{error_caching_min_ttl:"0",error_code:"403",response_code:"200",response_page_path:"/custom_404.html"}'
          aws_site_cdn_custom_error_codes: '[{\"error_caching_min_ttl\":\"0\",\"error_code\":\"403\",\"response_code\":\"200\",\"response_page_path\":\"/index.html\"},{\"error_caching_min_ttl\":\"0\",\"error_code\":\"404\",\"response_code\":\"200\",\"response_page_path\":\"/index.html\"}]'
          # You should own and have this domain available in R53
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: static-site-test-c
          aws_site_cdn_enabled: true
          aws_site_cdn_min_ttl: 33
          aws_site_cdn_default_ttl: 172803  # 48 hours
          aws_site_cdn_max_ttl: 604803      # 7 days          #aws_site_cdn_aliases: static-site-test.bitovi-sandbox.com,static-site-test2.bitovi-sandbox.com
          aws_site_cdn_response_headers_policy_id: "eaab4381-ed33-4a86-88ca-d9558dc6cd63"
          aws_r53_create_sub_cert: true # Will create and validate a cert for this sub-domain
          aws_site_source_include_hidden: true


      - name: Go down SPA
        if: false
        uses: bitovi/github-actions-deploy-static-site-to-aws@main
        #add-caching-to-cdn 
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1
  
          #aws_site_source_folder: .
          tf_action: 'destroy'
          tf_state_bucket_destroy: true
          aws_resource_identifier: bitovi-devops-training-ec2-gha-example-static-site
          #aws_site_cdn_custom_error_codes: '{error_caching_min_ttl:"0",error_code:"403",response_code:"200",response_page_path:"/custom_404.html"}'
          aws_site_cdn_custom_error_codes: '[{\"error_caching_min_ttl\":\"0\",\"error_code\":\"403\",\"response_code\":\"200\",\"response_page_path\":\"/index.html\"},{\"error_caching_min_ttl\":\"0\",\"error_code\":\"404\",\"response_code\":\"200\",\"response_page_path\":\"/index.html\"}]'
          # You should own and have this domain available in R53
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: static-site-test
          aws_site_cdn_enabled: true
          aws_site_cdn_min_ttl: 0
          aws_site_cdn_default_ttl: 172800  # 48 hours
          aws_site_cdn_max_ttl: 604800      # 7 days          #aws_site_cdn_aliases: static-site-test.bitovi-sandbox.com,static-site-test2.bitovi-sandbox.com
          aws_site_cdn_response_headers_policy_id: "eaab4381-ed33-4a86-88ca-d9558dc6cd63"
          aws_r53_create_sub_cert: true # Will create and validate a cert for this sub-domain
          aws_site_source_include_hidden: true
