name: Deploy-SBX

on:
  push:
    branches: [ feat/sbox-rds ]

permissions:
  contents: read

jobs:
  EC2-Deploy:
    # if the branch name of the PR does not contain 'skip-deploy'
    if: "!contains(github.head_ref, 'skip-deploy')"
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
    - id: deploy
      name: Deploy
      uses: bitovi/github-actions-deploy-docker-to-ec2@rds
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1
        enable_postgres: true

        # Provide a secret called `DOT_ENV` to append environment variables to the .env file
        # dot_env: ${{ secrets.DOT_ENV }}
        # stack_destroy: true
        # TODO:
        # postgres_vpc_id                 = "vpc-081abe910edab4281"
        # postgres_vpc_cidr               = "172.31.0.0/16"
        # postgres_subnets                = ["subnet-0f1b65df74adf6e87", "subnet-05d768eabcd7591ea", "subnet-082c8c6a0f81405d3"]
        postgres_subnets: "subnet-0f1b65df74adf6e87,subnet-05d768eabcd7591ea,subnet-082c8c6a0f81405d3"

        app_port: 3000

    - if: ${{ steps.deploy.outputs.vm_url != '' }}
      name: Print result created
      run: |
        echo "## VM Created! :rocket:" >> $GITHUB_STEP_SUMMARY
        echo " ${{ steps.deploy.outputs.vm_url }}" >> $GITHUB_STEP_SUMMARY
    - if: ${{ steps.deploy.outputs.vm_url == '' }}
      name: Print result destroyed
      run: |
        echo "## VM Destroyed! :boom:" >> $GITHUB_STEP_SUMMARY
        echo "Buckets and whole infrastructure should be gone now!" >> $GITHUB_STEP_SUMMARY