name: Deploy EKS Cluster

on:
  push:
    branches: [ deploy-eks ]
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: deploy
      uses: bitovi/github-actions-deploy-eks@main
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws_default_region: us-east-1

        input_helm_charts:
  
        bitops_code_only: 
        bitops_code_store: 
        tf_state_bucket_destroy: true
        tf_stack_destroy: true
        
        #aws_eks_create: true
        #aws_eks_region: 
        #aws_eks_security_group_name_master: 
        #aws_eks_security_group_name_worker: 
        #aws_eks_environment:
        #aws_eks_stackname: 
        #aws_eks_cidr_block:
        #aws_eks_workstation_cidr: 
        #aws_eks_availability_zones: 
        #aws_eks_private_subnets: 
        #aws_eks_public_subnets: 
        #aws_eks_cluster_name: 
        #aws_eks_cluster_log_types: 
        #aws_eks_cluster_version:
        #aws_eks_instance_type: 
        #aws_eks_user_data_file: 
        #aws_eks_ec2_key_pair:
        #aws_eks_store_keypair_sm: 
        #aws_eks_desired_capacity: 
        #aws_eks_max_size: 
        #aws_eks_min_size:
 
        aws_eks_create: true
        aws_eks_environment: qa
        aws_eks_stackname: qa-stack
        aws_eks_cluster_version: 1.25
        aws_eks_instance_type: t2.small

        aws_eks_max_size: 5
        aws_eks_min_size: 2
        aws_eks_desired_capacity: 3

        aws_eks_availability_zones: "us-east-1a,us-east-1f,us-east-1c"
        aws_eks_private_subnets: "10.0.1.0/24,10.0.2.0/24,10.0.3.0/24"
        aws_eks_public_subnets: "10.0.11.0/24,10.0.12.0/24,10.0.13.0/24"
