name: Deploy EKS Cluster

on:
  push:
    branches: [ deploy-eks ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Destroy EKS Cluster
      uses: bitovi/github-actions-deploy-eks@bitops-conditional-helm
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1

        tf_state_bucket_destroy: true
        tf_stack_destroy: true
        
    - name: Create EKS Cluster
      uses: bitovi/github-actions-deploy-eks@bitops-conditional-helm
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1
        
        tf_state_bucket_destroy: true
        
        #aws_eks_cluster_admin_role_arn: arn:aws:iam::755521597925:role/AWSReservedSSO_AdministratorAccess_402f22a297379e03
        aws_eks_create: true
        # input_helm_charts:
        #tf_stack_destroy: true
        prometheus-enable: true
        grafana-enable: true

    - name: Create EKS Cluster2
      uses: bitovi/github-actions-deploy-eks@bitops-conditional-helm
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1
        
        tf_state_bucket_destroy: true
        
        aws_eks_cluster_admin_role_arn: arn:aws:iam::755521597925:role/AWSReservedSSO_AdministratorAccess_402f22a297379e03
        aws_eks_create: true
        # input_helm_charts:
        #tf_stack_destroy: true
        prometheus-enable: true
        grafana-enable: true
        # loki-enable:
        # nginx-enable:
        
    - name: Destroy EKS Cluster 2
      uses: bitovi/github-actions-deploy-eks@bitops-conditional-helm
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1
  
        tf_state_bucket_destroy: true
        tf_stack_destroy: true
   # #- name: Create EKS Cluster
   #   uses: bitovi/github-actions-deploy-eks@legacy
   #   with:
   #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
   #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
   #     aws_default_region: us-east-1
   #    
   #     tf_state_bucket_destroy: true 

   #     aws_eks_create: true
   #     aws_eks_environment: qa
   #     aws_eks_stackname: qa-stack
            
    #- name: destroy0
    #  uses: bitovi/github-actions-deploy-temporal@gha-testing
    #  with:
    #    aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
    #    aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
    #    aws_default_region: us-east-1  
    #    input_helm_charts: helm
        
        #aws_aurora_enable: true
        #aws_eks_create: true

    #    tf_state_bucket_destroy: true
    #    tf_stack_destroy: true


#    - name: Recreate EKS Cluster
#      uses: bitovi/github-actions-deploy-eks@commons-bump
#      with:
#        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
#        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
#        aws_default_region: us-east-1
#  
#        tf_state_bucket_destroy: true
#        #tf_stack_destroy: true
#
#    - name: Destroy EKS Cluster
#      uses: bitovi/github-actions-deploy-eks@commons-bump
#      with:
#        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
#        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
#        aws_default_region: us-east-1
#  
#        tf_state_bucket_destroy: true
#        tf_stack_destroy: true
#
  
#    - name: destroy2
#      uses: bitovi/github-actions-deploy-eks@gha-testing
#      with:
#        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
#        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
#        aws_default_region: us-east-1#
#
#        input_helm_charts: helm
#  
#        bitops_code_only: 
#        bitops_code_store:  
#        tf_state_bucket_destroy: true
