name: Deploy D2EC2 Testing branch

on:
  push:
    branches: [ d2ec2 ]

permissions:
  contents: read
 
jobs:
  EC2-Deploy:
    # if the branch name of the PR does not contain 'skip-deploy'
    if: "!contains(github.head_ref, 'skip-deploy')"
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
    - id: destroy
      name: Destroy
      uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
      with:
        #ansible_skip: true

        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws_default_region: us-east-1
        #stack_destroy: true
        tf_state_bucket_destroy: true
        lb_create: false

        ec2_port_list: 3000
        app_port: 3000
        lb_port: 3000
        lb_healthcheck: TCP:22

        aws_vpc_id: vpc-081abe910edab4281
        aws_vpc_subnet_id: subnet-0f1b65df74adf6e87

        docker_remove_orphans: true
        docker_full_cleanup: true
