name: Deploy EKS Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: bitovi/github-actions-deploy-eks@vdeploy-eks

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        args: init
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Terraform Plan
      uses: hashicorp/terraform-github-actions@master
      with:
        args: plan -out=tfplan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions@master
      with:
        args: apply -auto-approve tfplan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
