name: Deploy EKS Cluster

on:
  push:
    branches: [ deploy-eks ]
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: bitovi/github-actions-deploy-eks@deploy-eks
      

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        args: init

    - name: Terraform Plan
      uses: hashicorp/terraform-github-actions@master
      with:
        args: plan -out=tfplan
      env:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}

    # - name: Terraform Apply
    #   uses: hashicorp/terraform-github-actions@master
    #   with:
    #     args: apply -auto-approve tfplan
    #   env:
    #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
    #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
