name: Deploy D2EC2 Testing branch

on:
  push:
    branches: [ d2ec2 ]

permissions:
  contents: read
 
jobs:
  EC2-Deploy:
    # if the branch name of the PR does not contain 'skip-deploy'
    if: "!contains(github.head_ref, 'skip-deploy')"
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
    - id: destroy
      name: Destroy
      uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
      with:
        #ansible_skip: true

        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws_default_region: us-east-1
        tf_state_bucket_destroy: true
        stack_destroy: true
        ec2_port_list: 3000
        app_port: 3000
        lb_port: 3000
        lb_healthcheck: "HTTP:3000"

        domain_name: bitovi-sandbox.com
        sub_domain: deleteme
        ec2_volume_size: 16
