name: Deploy EKS Cluster

on:
  push:
    branches: [ deploy-eks ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Create EKS Cluster tf-state-eks
      uses: bitovi/github-actions-deploy-eks@bitops-conditional-helm
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1
  
        tf_state_bucket_destroy: true
        tf_stack_destroy: true
        tf_state_file_name: tf-state-eks

    - name: Create EKS Cluster tf-state-aws
      uses: bitovi/github-actions-deploy-eks@bitops-conditional-helm
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1
  
        tf_state_bucket_destroy: true
        tf_stack_destroy: true

    - name: Create EKS Cluster tf-state
      uses: bitovi/github-actions-deploy-eks@bitops-conditional-helm
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1
  
        tf_state_bucket_destroy: true
        tf_stack_destroy: true
        tf_state_file_name: tf-state

    - name: Create EKS Cluster tf-state-aws_eks
      uses: bitovi/github-actions-deploy-eks@bitops-conditional-helm
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1
  
        tf_state_bucket_destroy: true
        tf_stack_destroy: true
        tf_state_file_name: tf-state-aws_eks
        
    - name: Create EKS Cluster tf-state-aws_eks2
      uses: bitovi/github-actions-deploy-eks@bitops-conditional-helm
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1
  
        tf_state_bucket_destroy: true
        tf_stack_destroy: true
        tf_state_file_name: tf-state-aws_eks2

    - name: Create EKS Cluster
      uses: bitovi/github-actions-deploy-eks@bitops-conditional-helm
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1
  
        tf_state_bucket_destroy: true
        #tf_stack_destroy: true
        
   # #- name: Create EKS Cluster
   #   uses: bitovi/github-actions-deploy-eks@legacy
   #   with:
   #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
   #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
   #     aws_default_region: us-east-1
   #    
   #     tf_state_bucket_destroy: true 

   #     aws_eks_create: true
   #     aws_eks_environment: qa
   #     aws_eks_stackname: qa-stack
            
    #- name: destroy0
    #  uses: bitovi/github-actions-deploy-temporal@gha-testing
    #  with:
    #    aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
    #    aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
    #    aws_default_region: us-east-1  
    #    input_helm_charts: helm
        
        #aws_aurora_enable: true
        #aws_eks_create: true

    #    tf_state_bucket_destroy: true
    #    tf_stack_destroy: true


#    - name: Recreate EKS Cluster
#      uses: bitovi/github-actions-deploy-eks@commons-bump
#      with:
#        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
#        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
#        aws_default_region: us-east-1
#  
#        tf_state_bucket_destroy: true
#        #tf_stack_destroy: true
#
#    - name: Destroy EKS Cluster
#      uses: bitovi/github-actions-deploy-eks@commons-bump
#      with:
#        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
#        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
#        aws_default_region: us-east-1
#  
#        tf_state_bucket_destroy: true
#        tf_stack_destroy: true
#
  
#    - name: destroy2
#      uses: bitovi/github-actions-deploy-eks@gha-testing
#      with:
#        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
#        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
#        aws_default_region: us-east-1#
#
#        input_helm_charts: helm
#  
#        bitops_code_only: 
#        bitops_code_store:  
#        tf_state_bucket_destroy: true
