name: Deploy EKS Cluster

on:
  push:
    branches: [ deploy-eks ]
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: deploy
      uses: bitovi/github-actions-deploy-eks@deploy-eks
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1

