name: Deploy GHR
on:
  push:
    branches: [ ecr-ecs-fargate ]
      

jobs:
  deploy-bucket-only:
    runs-on: ubuntu-latest
    steps:
    - name: Create ECR Registry
      id: create-ecr
      uses: bitovi/github-actions-deploy-aws-ecr-registry@main
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1
        
        tf_stack_destroy: true
        tf_state_bucket_destroy: true
        
        aws_ecr_repo_create: true
        aws_ecr_repo_type: 
        aws_ecr_repo_name: testing-repo-leo-v2
        aws_ecr_repo_mutable: true
        aws_ecr_repo_encryption_type: 
        aws_ecr_repo_encryption_key_arn:
        aws_ecr_repo_force_destroy: true
        aws_ecr_repo_image_scan: 
        aws_ecr_registry_scan_rule: 
        aws_ecr_registry_pull_through_cache_rules:
        aws_ecr_registry_scan_config:
        aws_ecr_registry_replication_rules_input:
        aws_ecr_repo_policy_attach:
        aws_ecr_repo_policy_create:
        aws_ecr_repo_policy_input:
        aws_ecr_repo_read_arn:
        aws_ecr_repo_write_arn:
        aws_ecr_repo_read_arn_lambda:
        aws_ecr_lifecycle_policy_input:
        aws_ecr_public_repo_catalog:
        aws_ecr_registry_policy_input:
        aws_ecr_additional_tags: '{\"CreatedBy\":\"Leo\",\"Deleteable\":\"Yes\"}'

    #- name: Build tag and push container
    #  id: tag-and-push
    #  uses: bitovi/github-actions-ecr-publish@main
    #  with:
    #    checkout: true
    #    aws_login: true
    #    aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
    #    aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
    #    aws_default_region: us-east-1
    #    aws_ecr_repo_name: testing-repo-leo-v2
    #    #image_tag:
    #    #org_name:
    #    #build_args:
    #    use_latest: true
    #    working_directory: container

    - name: Create an RDS DB
      id: create-rds
      uses: bitovi/github-actions-deploy-rds@testing
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1
        
        tf_stack_destroy: true
        tf_state_bucket_destroy: true
        
        aws_rds_db_enable: true
