name: Deploy GHR
on:
  push:
    branches: [ ecr-ecs-fargate ]
      

jobs:
  deploy-bucket-only:
    runs-on: ubuntu-latest
    steps:
#    - name: Build tag and push container
#      id: tag-and-push
#      uses: bitovi/github-actions-ecr-publish@main
#      with:
#        checkout: true
#        aws_login: true
#        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
#        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
#        aws_default_region: us-east-1
#        aws_ecr_repo_name: testing-repo-leo
        #image_tag:
        #org_name:
        #build_args:
#        use_latest: true
#        working_directory: container

    - name: Create an RDS DB
      uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws_default_region: us-east-1

        stack_destroy: true
        tf_state_bucket: ecs-leo-testing
        tf_state_bucket_destroy: 
        aws_ecs_enable: true
        aws_ecs_app_image: 755521597925.dkr.ecr.us-east-1.amazonaws.com/testing-repo-leo:d2ec2,755521597925.dkr.ecr.us-east-1.amazonaws.com/testing-repo-leo:hello
        aws_ecs_app_cpu: 2048
        aws_ecs_app_mem: 4096
        aws_ecs_assign_public_ip: true
        aws_ecs_container_port: 3000,3001
        aws_ecs_lb_port: 3000,3001
        aws_vpc_id: vpc-081abe910edab4281
        aws_vpc_subnet_id: subnet-056feca23aa09e324
        
        tf_state_file_name_append: tbd
