name: Deploy SAM
on:
  push:
    branches: [ serverless ]
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SAM Deploy
      uses: bitovi/github-actions-deploy-serverless-website@DEVOPS-792-GHA-deploy-to-s3-cloudfront-cert
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1
        aws_additional_tags: `{"Status": "debug"}`

        tf_action: plan
        tf_plan_show_details: false
        tf_state_bucket:
        tf_state_bucket_destroy: true

        aws_spa_file_sources: index.html
        aws_spa_file_keys:
        aws_spa_website_bucket_name: 
        aws_spa_cdn_enabled:
        aws_spa_cdn_root_object:

        aws_r53_domain_name:
        aws_r53_sub_domain_name:
        aws_r53_root_domain_deploy:
        aws_r53_enable_cert:
        aws_r53_cert_arn:
        aws_r53_create_root_cert:
        aws_r53_create_sub_cert: