name: Deploy GHR
on:
  push:
    branches: [ ecr-ecs-fargate ]
jobs:
  deploy-bucket-only:
    runs-on: ubuntu-latest
    steps:
    - name: Create an ECS-Fargate deploy
      uses: bitovi/github-actions-deploy-aws-ecr-registry@import-code
      id: ecr
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws_default_region: us-east-1
        tf_action: destroy
        tf_stack_destroy: true
        #tf_state_bucket: bitovi-devops-training-ec2-gha-example-ecr-ecs-fargate-tf-stat2
        tf_state_bucket_destroy: true
        #aws_ecr_repo_create: true
