name: simple-storybook
on:
  workflow_dispatch:
    inputs:
      tf_stack_destroy:
        description: 'Destroy the Terraform stack'
        required: false
        type: boolean
        default: true
  push:
    branches: [ simple-storybook ]


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0