name: Destroy

on:
  workflow_dispatch:
    inputs:
      aws_resource_identifier:
        description: Resource Identifier for deployed resources
  pull_request:
    types: [ closed ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: destroy
      uses: bitovi/github-actions-node-app-to-aws-vm@tf-destroy
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_DEVOPS_TRAINING}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVOPS_TRAINING}}
        aws_default_region: us-east-1
        stack_destroy: true
        # Provide a secret called `DOT_ENV` to append environment variables to the .env file
        # dot_env: ${{ secrets.DOT_ENV }}
        aws_resource_identifier: ${{ github.event.inputs.aws_resource_identifier }}
        app_port: 3000