name: simple-ecr
on:
  workflow_dispatch:
    inputs:
      tf_stack_destroy:
        description: 'Destroy the Terraform stack'
        required: false
        type: boolean
        default: true
  push:
    branches: [ simple-ecr ]
jobs:
  simple-ecr:
    runs-on: ubuntu-latest
    steps:
    - id: ecr-deploy
      uses: bitovi/github-actions-deploy-aws-ecr-registry@v0.1.1
      # https://github.com/bitovi/github-actions-deploy-aws-ecr-registry/
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws_default_region: us-east-1

        #aws_resource_identifier: 
        #aws_additional_tags:

        tf_stack_destroy: ${{ inputs.tf_stack_destroy }}
        #tf_state_file_name: 
        tf_state_file_name_append: ecr-registry
        #tf_state_bucket: 
        #tf_state_bucket_destroy: ${{ inputs.tf_stack_destroy }}

        aws_ecr_repo_create: true
        aws_ecr_repo_type: private # default
        #aws_ecr_repo_name: 
        #aws_ecr_repo_mutable: 
        #aws_ecr_repo_encryption_type: AES256
        #aws_ecr_repo_encryption_key_arn:
        aws_ecr_repo_force_destroy: ${{ inputs.tf_stack_destroy }}
        aws_ecr_repo_image_scan: true #default
        #aws_ecr_registry_scan_rule:
        #aws_ecr_registry_pull_through_cache_rules:
        #aws_ecr_registry_scan_config:
        #aws_ecr_registry_replication_rules_input:
        #aws_ecr_repo_policy_attach:
        #aws_ecr_repo_policy_create:
        #aws_ecr_repo_policy_input:
        #aws_ecr_repo_read_arn:
        #aws_ecr_repo_write_arn:
        #aws_ecr_repo_read_arn_lambda:
        #aws_ecr_lifecycle_policy_input:
        #aws_ecr_public_repo_catalog:
        #aws_ecr_registry_policy_input:
        #aws_ecr_additional_tags:
