name: Deploy Cluster
on:
    push:
      branches: [pure-eks]

jobs:
  Deploy-Cluster:
    runs-on: ubuntu-latest
    steps:
    - name: Create EKS Cluster
      uses: bitovi/github-actions-deploy-eks@v0.1.1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws_eks_cluster_name: bitovi-eks-example
        tf_state_bucket: bitovi-eks-example-terraform-state
        #aws_eks_instance_type: t3a.large
        #tf_stack_destroy: true
        tf_state_bucket_destroy: true