name: Jira-destroy
on:
  workflow_dispatch:
    inputs:
      aws_resource_identifier:
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
    - id: destroy
      name: Destroy
      uses: bitovi/github-actions-deploy-docker-to-ec2@v0.5-delete
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_JIRA_INTEGRATIONS}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_JIRA_INTEGRATIONS}}
        aws_default_region: us-east-1
        aws_resource_identifier: ${{ github.event.inputs.aws_resource_identifier }}


        stack_destroy: "true"
        tf_state_bucket_destroy: true

        # Provide a secret called `DOT_ENV` to append environment variables to the .env file
        dot_env: ${{ secrets.DOT_ENV }}

        domain_name: bitovi-jira.com
        app_port: 3000
