name: Man-SQL-apply

on:
  workflow_dispatch:
    inputs:
      secret_name:
        type: string
        description: "Database secret name"
        required: true
      scripts_path:
        type: string
        description: "Path containing SQL files"
        required: true
        default: 'sql-files'
      dry_run:
        type: boolean
        required: true
        default: true

permissions:
  contents: read
 
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Apply SQL files
        uses: bitovi/github-actions-apply-sql-files-to-postgres@main
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1 
          aws_secret_name: ${{ inputs.secret_name }}
          sql_scripts_path: ${{ inputs.scripts_path }}
          dry_run: ${{ inputs.dry_run }}
