name: Production CI/CD

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build-and-deploy:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    uses: ./.github/workflows/build_and_deploy.yaml
    with:
      image_tag: ${{ github.run_id }}
      environment: production
    secrets: inherit
    concurrency:
      group: ecr-deploy-production
      cancel-in-progress: true
