name: simple-rds
on:
  workflow_dispatch:
    inputs:
      tf_stack_destroy:
        description: 'Destroy the Terraform stack'
        required: false
        type: boolean
        default: true
      aws_ecr_repo_name:
        description: 'Name of the ECR repository'
        required: true
        type: string
        default: ecr-repo
  push:
    branches: [ simple-rds ]

jobs:
  simple-rds:
    runs-on: ubuntu-latest
    steps:
      - id: RDS-deploy
        uses: bitovi/github-actions-deploy-rds@v0
        # https://github.com/bitovi/github-actions-deploy-rds
        with:
          #aws_resource_identifier:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: 'us-east-1'

          tf_stack_destroy: false
          tf_state_bucket_destroy: false
          #tf_state_file_name_append:
          # tf_state_file_name:
          # tf_state_bucket:
          
          aws_rds_db_enable: true
          aws_rds_db_proxy: false
          #aws_rds_db_identifier:
          aws_rds_db_ingress_allow_all: true

          aws_rds_db_allocated_storage: 10
          aws_rds_db_max_allocated_storage: 20
          aws_rds_db_storage_encrypted: true
          aws_rds_db_instance_class: db.t4g.medium

          #aws_rds_db_monitoring_interval: 60
          #aws_rds_db_performance_insights_enable: true
          #aws_rds_db_performance_insights_retention: 7
          #aws_rds_db_insights_mode: standard

          aws_rds_db_user: dbuser
          aws_rds_db_publicly_accessible: true
          aws_rds_db_engine_version: 16.8

          #aws_rds_db_auto_minor_version_upgrade: true
          #aws_rds_db_backup_retention_period: 7
          #aws_rds_db_backup_window: "03:00-04:00"
          #aws_rds_db_copy_tags_to_snapshot: true
          #aws_rds_db_apply_immediately: true