name: Simple-D2EC2 deploy
on:
  push:
    branches: [ simple-d2ec2 ]

env:
  TF_DESTROY: 'false'

jobs:
  Simple-D2EC2-Deploy:
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 80
          #aws_lb_type: alb
          #aws_alb_enable_waf: false
          tf_stack_destroy: false

      - id: deploy-again
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 80
          #aws_lb_type: alb
          #aws_alb_enable_waf: false
          tf_stack_destroy: false

      - id: deploy-new
        uses: bitovi/github-actions-deploy-docker-to-ec2@testing
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 80
          #aws_lb_type: alb
          #aws_alb_enable_waf: false
          tf_stack_destroy: false
