name: Simple-D2EC2 deploy
on:
  push:
    branches: [ simple-d2ec2 ]

env:
  TF_DESTROY: 'false'

jobs:
  Destroy-D2EC2-Deploy:
    runs-on: ubuntu-latest
    if: false
    steps:
      - id: elb
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 80
          aws_elb_create: true
          #aws_lb_type: alb
          #aws_alb_enable_waf: false
          tf_stack_destroy: true
          tf_state_bucket_destroy: true
  
  Destroy-D2EC2-Deploy-new:
    runs-on: ubuntu-latest
    if: false
    steps:
      - id: deploy-new0
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_resource_identifier: new-alb-and-waf-to-ec2

          aws_r53_enable: false
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2n
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 80
          #aws_lb_type: alb
          #aws_alb_enable_waf: false
          tf_stack_destroy: true
          tf_state_bucket_destroy: true

  Test-3rd-D2EC2-Deploy-new2:
    runs-on: ubuntu-latest
    if: false
    steps:
      - id: deploy-new0
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_resource_identifier: new-alb-and-waf-to-ec2-3

          aws_r53_enable: false
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2n-3
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 80
          #aws_lb_type: alb
          #aws_alb_enable_waf: false
          tf_stack_destroy: true
          tf_state_bucket_destroy: true

#############################
  Simple-D2EC2-Deploy:
    runs-on: ubuntu-latest
    if: false
    steps:
      - id: destroy
        name: Deploy with ELB and R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          tf_stack_destroy: true

      - id: elb-no-r53
        name: Deploy with ELB and R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: true
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true
          #aws_lb_type: alb
          #aws_alb_enable_waf: false
          tf_stack_destroy: false

      - id: elb-no-r53-2
        name: Deploy with ELB and R53 - Check this one for diffs
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: true
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true
          #aws_lb_type: alb
          #aws_alb_enable_waf: false
          tf_stack_destroy: false

      - id: elb
        name: Deploy without R53 - Check this one for diffs
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1
        with:
          ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true
          #aws_lb_type: alb
          #aws_alb_enable_waf: false
          tf_stack_destroy: false

      - id: elb-2
        name: Deploy without R53 - Check this one for diffs
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true
          #aws_lb_type: alb
          #aws_alb_enable_waf: false
          tf_stack_destroy: false

      - id: elb-r53
        name: Deploy with R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1
        with:
          ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: true
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true
          #aws_lb_type: alb
          #aws_alb_enable_waf: false
          tf_stack_destroy: false

      - id: elb-no-r53-v2
        name: Deploy with ELB and R53 - Check this one for diffs
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: true
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true
          #aws_lb_type: alb
          #aws_alb_enable_waf: false
          tf_stack_destroy: false

      - id: no-elb-no-r53
        name: Deploy with ELB and remove R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1
        with:
          ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_listen_port: 3000
          aws_elb_create: true
          #aws_lb_type: alb
          #aws_alb_enable_waf: false
          tf_stack_destroy: false

      - id: no-elb-no-r53-2
        name: Deploy with ELB and remove R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true
          #aws_lb_type: alb
          #aws_alb_enable_waf: false
          tf_stack_destroy: false

      - id: r53-yes-no-elb
        name: Deploy with R53 and remove ELB
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: true
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: false
          aws_alb_create: true
          aws_alb_app_port: 3000
          #aws_lb_type: alb
          aws_waf_enable: true
          tf_stack_destroy: false

      - id: r53-yes-no-elb2
        name: Deploy with R53 and remove ELB (alternate)
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: true
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: false
          #aws_lb_type: alb
          #aws_alb_enable_waf: false
          tf_stack_destroy: false

      - id: r53-yes-no-elb2-2
        name: Deploy with R53 and remove ELB (alternate)
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: true
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: false
          #aws_lb_type: alb
          #aws_alb_enable_waf: false
          tf_stack_destroy: false
          aws_alb_redirect_enable: false
          aws_alb_www_to_apex_redirect: true

      - id: r53-yes-no-elb2-3
        name: Deploy with R53 and remove ELB (alternate)
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: true
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_listen_port: 3000
          aws_elb_create: false
          #aws_lb_type: alb
          #aws_alb_enable_waf: false
          tf_stack_destroy: false
          aws_alb_redirect_enable: true
          aws_alb_www_to_apex_redirect: true

  Simple-D2EC2-Deploy-new:
    runs-on: ubuntu-latest
    if: false
    steps:
      - id: destroy-new
        name: Deploy with R53, ALB, and WAF
        if: true
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_resource_identifier: new-alb-and-waf-to-ec2

          tf_stack_destroy: true

      - id: deploy-r53-enable-alb-waf
        #if: false
        name: Deploy with R53, ALB, and WAF
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          ansible_skip: false
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_resource_identifier: new-alb-and-waf-to-ec2

          aws_r53_enable: false
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2n
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro

          tf_stack_destroy: false

          aws_elb_app_port: 3000
          aws_elb_create: false
          aws_alb_create: true
          aws_alb_app_port: 3000

          aws_waf_enable: true
          aws_waf_logging_enable: false
          aws_waf_rule_anonymous_ip: true

      - id: deploy-new0
       #if: false
        name: Deploy without R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_resource_identifier: new-alb-and-waf-to-ec2

          aws_r53_enable: false
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2n
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000

      - id: deploy-r53
        #if: false
        name: Deploy with R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_resource_identifier: new-alb-and-waf-to-ec2

          aws_r53_enable: true
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2n
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro

          aws_elb_create: false
          aws_elb_app_port: 3000

      - id: deploy-r53-enable-elb
       #if: false
        name: Deploy with R53 and ELB
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_resource_identifier: new-alb-and-waf-to-ec2

          aws_r53_enable: true
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2n
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro

          aws_elb_create: true
          aws_elb_app_port: 3000

      - id: deploy-r53-enable-alb
        #if: false
        name: Deploy with R53 and ALB
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          #ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_resource_identifier: new-alb-and-waf-to-ec2

          aws_r53_enable: true
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2n
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true
          aws_alb_create: true
          aws_alb_app_port: 3000
          aws_alb_redirect_enable: true
          aws_alb_www_to_apex_redirect: true

      - id: deploy-r53-enable-alb-ports
        #if: false
        name: Deploy with R53 and ALB - shift ports
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_resource_identifier: new-alb-and-waf-to-ec2

          aws_r53_enable: false
          #aws_r53_domain_name: bitovi-sandbox.com
          #aws_r53_sub_domain_name: sd2ec2n
          #aws_r53_create_sub_cert: false
          aws_r53_enable_cert: true
          aws_r53_cert_arn: "arn:aws:acm:us-east-1:755521597925:certificate/c2ee1a5f-3fd9-406d-b0a2-5c655142579f"

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_listen_port: 3000
          aws_elb_create: true
          aws_alb_create: true
          #aws_alb_app_port: 3000
          aws_alb_listen_port: 3000
          aws_alb_redirect_enable: true
          aws_alb_www_to_apex_redirect: true

          aws_waf_enable: true
          aws_waf_logging_enable: false
          aws_waf_rule_anonymous_ip: false
          aws_waf_rule_anonymous_ip_priority: 21


      - id: deploy-r53-enable-alb-waf-final
        #if: false
        name: Deploy with R53, ALB, and WAF
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_resource_identifier: new-alb-and-waf-to-ec2

          aws_r53_enable: false
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2n
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro

          tf_stack_destroy: false

          aws_elb_app_port: 3000
          aws_elb_create: false
          aws_alb_create: true
          aws_alb_app_port: 3000
          aws_alb_listen_port: 3000

          aws_waf_enable: true
          aws_waf_logging_enable: false
          aws_waf_rule_anonymous_ip: true
          aws_alb_redirect_enable: true
          aws_alb_www_to_apex_redirect: true

      - id: deploy-r53-enable-alb-waf-final-2
        #if: false
        name: Deploy with R53, ALB, and WAF
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_resource_identifier: new-alb-and-waf-to-ec2

          aws_r53_enable: false
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2n
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro

          tf_stack_destroy: false

          aws_elb_app_port: 3000
          aws_elb_create: false
          aws_alb_create: true
          aws_alb_app_port: 3000

          aws_waf_enable: true
          aws_waf_logging_enable: false
          aws_waf_rule_anonymous_ip: true
          aws_alb_redirect_enable: true
          aws_alb_www_to_apex_redirect: true

      - id: final-go
        name: Deploy with R53, ALB, and WAF
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_resource_identifier: new-alb-and-waf-to-ec2

          aws_r53_enable: true
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: sd2ec2n
          aws_r53_create_sub_cert: true

          aws_ec2_instance_type: t3.micro

          tf_stack_destroy: false

          aws_elb_app_port: 3000
          aws_elb_create: false
          aws_alb_create: true
          aws_alb_app_port: 3000
          aws_alb_listen_port: 3000
          aws_waf_enable: true
          aws_waf_logging_enable: false
          aws_waf_rule_anonymous_ip: true
          aws_alb_redirect_enable: true
          aws_alb_www_to_apex_redirect: true

  Side-go-D2EC2-Deploy-new:
    runs-on: ubuntu-latest
    if: false
    steps:
      - id: final-go
        name: Deploy with R53, ALB, and WAF
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          ansible_skip: true
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_resource_identifier: new-alb-and-waf-to-ec2

          aws_r53_enable: true
          aws_r53_domain_name: lodiaz.com.ar
          aws_r53_sub_domain_name: some
          #aws_r53_create_sub_cert: true
          aws_r53_create_root_cert: true
          #aws_r53_root_domain_deploy: true

          aws_ec2_instance_type: t3.micro

          tf_stack_destroy: false

          aws_elb_app_port: 3000
          aws_elb_create: false
          aws_alb_create: true
          aws_alb_app_port: 3000
          aws_alb_listen_port: 3000
          aws_waf_enable: true
          aws_waf_logging_enable: false
          aws_waf_rule_anonymous_ip: true
          aws_alb_redirect_enable: true
          aws_alb_www_to_apex_redirect: true


#############################
  Simple-docker-backup-test-Deploy:
    runs-on: ubuntu-latest
    if: false
    steps:
      - id: a0
        if: false
        name: Deploy with ELB and R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1
          tf_stack_destroy: true
          aws_r53_enable: false

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true

          docker_repo_app_directory_cleanup: true
      - id: a1
        if: false
        name: Deploy with ELB and R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true

          docker_repo_app_directory_cleanup: true

      - id: a2
        if: false
        name: Deploy with ELB and R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true

          docker_repo_app_directory_cleanup: true
  
      - id: a3
        if: false
        name: Deploy with ELB and R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true

          docker_repo_app_directory_cleanup: true

      - id: a4
        if: false
        name: Deploy with ELB and R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true

          docker_repo_app_directory_cleanup: true

      - id: a5
        if: false
        name: Deploy with ELB and R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true

          docker_repo_app_directory_cleanup: true
  
      - id: a6
        if: false
        name: Deploy with ELB and R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-testing
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true

          docker_repo_app_directory_cleanup: true
          docker_backup_retention: 4


####
  Cleanup:
    runs-on: ubuntu-latest
    if: false
    steps:
      - id: destroy-backup-test
        name: Destroy Simple-docker-backup-test-Deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@alb-waf-certificates-docker-cleanup
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1
          tf_stack_destroy: true
          aws_r53_enable: false
          tf_state_bucket_destroy: true
          aws_resource_identifier: bitovi-commons-testing-elb-logs-bucket-bitovi-commons-testi61

  Cleanup2:
    runs-on: ubuntu-latest
    if: false
    steps:
      - id: destroy-backup-test
        name: Destroy Simple-docker-backup-test-Deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@alb-waf-certificates-docker-cleanup
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1
          tf_stack_destroy: true
          aws_r53_enable: false
          tf_state_bucket_destroy: true
          aws_resource_identifier: bitovi-commons-testing-elb-logs-bucket-bitovi-commons-testing64o

  Cleanup3:
    runs-on: ubuntu-latest
    if: false
    steps:
      - id: destroy-backup-test
        name: Destroy Simple-docker-backup-test-Deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@alb-waf-certificates-docker-cleanup
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1
          tf_stack_destroy: true
          aws_r53_enable: false
          tf_state_bucket_destroy: true
          aws_resource_identifier: bitovi-commons-testing-elb-logs-bucket-bitovi-commons-testing63

#############################
  Simple-docker-backup-test-elb-bucket-naming:
    runs-on: ubuntu-latest
    if: true
    steps:
      - id: a0
        if: false
        name: Deploy with ELB and R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@alb-waf-certificates-docker-cleanup
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1
          tf_stack_destroy: true
          aws_r53_enable: false

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true
          aws_resource_identifier: bitovi-commons-testing-elb-logs-bucket-bitovi-commons-test60
          tf_state_bucket_destroy: true

          docker_repo_app_directory_cleanup: true
      - id: a1
        #if: false
        name: Deploy with ELB and R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@alb-waf-certificates-docker-cleanup
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true

          docker_repo_app_directory_cleanup: true
          aws_resource_identifier: bitovi-commons-testing-elb-logs-bucket-bitovi-commons-tes59

      - id: a2
        if: false
        name: Deploy with ELB and R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@alb-waf-certificates-docker-cleanup
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true
          aws_elb_access_log_bucket_name: "bitovi-commons-testing-elb-logs-bucket-bitovi-commons-testing-elb-logs-bucket"

          docker_repo_app_directory_cleanup: true
  
      - id: a3
        if: false
        name: Deploy with ELB and R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@alb-waf-certificates-docker-cleanup
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true
          aws_elb_access_log_bucket_name: "bitovi-commons-testing-elb-logs-bucket-bitovi-commons-testing12"

          docker_repo_app_directory_cleanup: true

      - id: a4
        if: false
        name: Deploy with ELB and R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@alb-waf-certificates-docker-cleanup
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true
          aws_elb_access_log_bucket_name: "bitovi-commons-testing-elb-logs-bucket-bitovi-commons-testing124"

          docker_repo_app_directory_cleanup: true

      - id: a5
        if: false
        name: Deploy with ELB and R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@alb-waf-certificates-docker-cleanup
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true
         
          aws_alb_create: true
          aws_alb_access_log_enabled: true
          docker_repo_app_directory_cleanup: true
  
      - id: a6
        if: false
        name: Deploy with ELB and R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@alb-waf-certificates-docker-cleanup
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true

          aws_alb_create: true
          aws_alb_access_log_enabled: true
          aws_alb_access_log_bucket_name: "bitovi-commons-testing-elb-logs-bucket-bitovi-commons-testing12"

          docker_repo_app_directory_cleanup: true
          docker_backup_retention: 4

      - id: a7
        if: false
        name: Deploy with ELB and R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@alb-waf-certificates-docker-cleanup
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true

          aws_alb_create: true
          aws_alb_access_log_enabled: true
          aws_alb_access_log_bucket_name: "bitovi-commons-testing-elb-logs-bucket-bitovi-commons-testing123"

          docker_repo_app_directory_cleanup: true
          docker_backup_retention: 4

      - id: a8
        if: false
        name: Deploy with ELB and R53
        uses: bitovi/github-actions-deploy-docker-to-ec2@alb-waf-certificates-docker-cleanup
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: false

          aws_ec2_instance_type: t3.micro
          aws_elb_app_port: 3000
          aws_elb_create: true

          aws_alb_create: true
          aws_alb_access_log_enabled: true
          aws_alb_access_log_bucket_name: "bitovi-commons-testing-elb-logs-bucket-bitovi-commons-testing1234"

          docker_repo_app_directory_cleanup: true
          docker_backup_retention: 4