name: Simple-Signoz deploy
on:
  push:
    branches: [ simple-signoz ]

jobs:
  Simple-Signoz-Deploy:
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@main #alb-test
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_r53_enable: true
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: signoz
          #aws_r53_create_sub_cert: true
          aws_elb_app_port: 8080,4318
          aws_elb_listen_port: 443,4318
          aws_elb_healthcheck: "HTTP:8080"
          #aws_elb_create: false
          #tf_stack_destroy: true
          tf_state_bucket_destroy: true 

          aws_ec2_instance_root_vol_size: 30
          aws_ec2_instance_type: t3.large
          aws_ec2_port_list: 8080,4318
          #aws_ec2_allowed_cidr: 
          #ansible_skip: false

          docker_repo_app_directory: ./signoz/deploy/docker