name: Staging CI/CD

on:
  pull_request:
    branches: [simple-ecr-ecs-dockerfile]
    types: [closed]
  push:
    branches: [main, simple-ecr-ecs-dockerfile]

jobs:
  build-and-deploy:
    #if: >
    #  github.event_name == 'workflow_dispatch' ||
    #  (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    uses: ./.github/workflows/build_and_deploy.yaml
    with:
      image_tag: ${{ github.run_id }}
      environment: staging
    secrets: inherit
    concurrency:
      group: ecr-deploy-staging
      cancel-in-progress: true