name: Staging CI/CD lala
run-name: Staging CI/CD Workflow ${{ github.run_id }}-${{ github.event_name }}

on:
  workflow_dispatch:
    inputs:
      test01:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test02:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test03:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test04:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test05:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test06:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test07:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test08:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test09:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test10:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test11:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test12:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test13:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test14:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test15:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test16:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test17:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test18:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test19:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test20:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test21:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test22:
        description: 'Test input to check max ammount'
        type: string
        required: false
      test23:
        description: 'Test input to check max ammount'
        type: string
        required: false
  pull_request:
    branches: [simple-ecr-ecs-dockerfile]
    types: [closed]
  push:
    branches: [main, simple-ecr-ecs-dockerfile]

jobs:
  build-and-deploy:
    #if: >
    #  github.event_name == 'workflow_dispatch' ||
    #  (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    uses: ./.github/workflows/build_and_deploy.yaml
    with:
      image_tag: ${{ github.run_id }}
      environment: staging
    secrets: inherit
    concurrency:
      group: ecr-deploy-staging
      cancel-in-progress: true