name: v0.5-destroy
on:
  workflow_dispatch:
    inputs:
      aws_resource_identifier:
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
    - id: destroy
      name: Destroy
      uses: bitovi/github-actions-deploy-docker-to-ec2@v0.5-delete
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws_default_region: us-east-1
        aws_resource_identifier: ${{ github.event.inputs.aws_resource_identifier }}

        stack_destroy: "true"
        tf_state_bucket_destroy: true